name: Build Grammar Packages

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  Grammars:
    runs-on: ubuntu-latest

    steps:
      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: tree-sitter-cli
        run: npm install -g tree-sitter-cli

      - name: Emscripten
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: latest
      
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build grammars
        run: python ./.github/scripts/grammars/build.py

      - name: Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Grammars Job"
          branch: master
          file_pattern: 'grammars/**'
